### ISSUE TITLE
pip install fails on colab

### ISSUE THREAD

**Issue by Deamoner** [sidward14/gan-lab#1]
Collecting gan-lab
  Using cached https://files.pythonhosted.org/packages/41/d7/32e3e9e72913a5aededf9e355c90044e833dea6374cb52cb20061286fa06/gan-lab-0.2.4.tar.gz
Requirement already satisfied: numpy>=1.17.2 in /usr/local/lib/python3.6/dist-packages (from gan-lab) (1.18.4)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.6/dist-packages (from gan-lab) (7.0.0)
Requirement already satisfied: matplotlib>=3.1.1 in /usr/local/lib/python3.6/dist-packages (from gan-lab) (3.2.1)
ERROR: Could not find a version that satisfies the requirement indexed.py>=0.0.1 (from gan-lab) (from versions: none)
ERROR: No matching distribution found for indexed.py>=0.0.1 (from gan-lab)

**Comment by sidward14** [comment]
Should be fixed now. The developer of the indexed.py package changed the name from indexed.py to indexed in setuptools and changed some of his code (which is mostly just refactoring).

I changed setup.py and requirements.txt to reflect this. I also quickly trained a few StyleGANs and ProGANs (the 2 GANs where the IndexedOrderedDict class is used) and didn't come across any problems.

In the long run, I don't want to rely on the possibility of gan-lab breaking again from another update to indexed down the road, so I'm going to remove dependency on it and implement another way. 

I'll leave this issue open a few days longer in case you (or someone else) find something.
